### ISSUE TITLE
selection of "current" chatfile

### ISSUE THREAD

**Issue by webwizrd** [3vi1/IMP#35]
When playing with 2 characters (2 EVE clients) on Windows, 2 chatfiles are created per channel in the logs directory. If I log off with the char that logged on second, IMP stops updating.

I think IMP picks up the chatfile with most recent _created date_ for a channel as info source. With the last-to-log-in character now logged off, this latest created file will not be updated.
If you made IMP use the file with most recent _changed date_ , this problem would go away.

**Comment by 3vi1** [comment]
This problem is actually due to something Microsoft broke... er, "optimized", in NTFS around the time of Windows Vista:  File modification timestamps no longer get updated until the file handle is closed.  Since EVE leaves the file open for write until you log off, its timestamp never gets updated.

This is the same reason I had to write the fallback poller code for Windows to go look at the file size vs. date to know when it is changed, rather than just use the filewatcher OS hook as is done in Linux.

I have a pretty straight-forward solution in mind, but I need to test it to make sure it doesn't impact performance too negatively.  If it works, this will probably fix bug #28 as well.  I'll shoot for having this released by Oct. 23 if all goes well.
