### ISSUE TITLE
Getting other peoples intl?

### ISSUE THREAD

**Issue by Pocketfrog** [3vi1/IMP#53]
i was just looking at the messages in imp, and noticed some guy called Khasm Kaotiqa from CVA alliance having a good rant about some guy being in a red alliance. Now ordinarily someone ranting in intl channel would just amuse me, but...I am in Co2 and not CVA and am not in their intl channel for obvious reasons on account they would be mad. so why oh why am I getting CVA intl?
I did a screen shot.
http://prntscr.com/iw9r02
That *imp* channel is not in my IMP intl channels. So I was just wondering what is going on? Am I doing something wrong or is imp picking up other channels intl randomly?

**Comment by 3vi1** [comment]
I'm Khasm Kaotiqa.  The message you got was because you pressed [Ctrl-C, Ctrl-C].  Which does a check against the CVA web services for KOS status (because I'm in CVA) on whomever you have highlighted.  The message isn't actually coming from a channel, but the program itself.

You can disable the KOS checking from the Settings | Options | KOS Checking tab so that my avatar won't be complaining about your company.  :)

It's on my list to, somewhere down the road, make this option more configurable so that alliances can define/use their own KOS databases.

**Comment by Pocketfrog** [comment]
hehehe ok! well that's that solved then. I was kinda hoping i could have a rant in your intl channels as well as mine. :) thanks for the answer
