### ISSUE TITLE
Some Ideas for a better Uxp

### ISSUE THREAD

**Issue by ppfeufer** [3vi1/IMP#6]
» Move the chat to the right side, or t least give us the option to do so. If you are not asian heritage, you tendo to start looking at the left side first, and since the map is teh most important thing in this app, it's currently only the second element your forcus goes to, that's a bit suboptimal.

» Use system font only. There is no need to be able to have all fonts installed on the system available for choice. Just use the system font, so the app fits in better into the system and with other applications. Integrates better into the system. Also it has a better readability.

» Don't parse hundrets of logfiles at the startup. Makes the thing slow starting and tells me that I am in 3 different locations when I only have 1 client logged in. Deselcting a pilot from the menu doesn't work to fix this.

» Mark system when I click in the chat at an entry only for a brief time, not permanently. It's confusing.

» Better map rendering, especially for fonts. Has a terrible readability.

» Make hyperlinks in chat clickable. Helps for fast viewing D-Scans and stuff.

Just for comparison (left IMP, right Vintel)
![screenie_139](https://cloud.githubusercontent.com/assets/2989985/24833185/6a7d9df4-1cc1-11e7-9776-69cfd640fd97.png)
At the moment I prefer Vintel because of the better UI and way better readability. If you get that with IMP, that would be awesome.

Thank you.

**Comment by 3vi1** [comment]
> Move the chat to the right side

In a near-future release, it will be dockable.  This has been my plan all along, I just haven't gotten to it yet.

> Use system font only.

No way; delete all the fonts off your system except for the system font.  This is a cross-platform app, and the "system font" on every one of them is different and not always the desirable choice.  On Linux, the system font can be different for every DE a user might use.

> Don't parse hundrets of logfiles at the startup

It doesn't.  It only reads the local and intel logs from the last 24 hours, and only the last 50 messages from the intel logs.  It has to read the last full local log to correctly ascertain your position.

> Mark system when I click in the chat at an entry only for a brief time, not permanently. It's confusing.

I'll consider making this an option.

> Better map rendering, especially for fonts. Has a terrible readability.

Change your font selections.  I don't develop it on Windows and the readability is great on my Linux desktop.

> Make hyperlinks in chat clickable. Helps for fast viewing D-Scans and stuff.

That's on my roadmap for near-future as well.

> Just for comparison

For some reason, Qt doesn't seem to be aliasing in the SVG view on your system.  You've got jaggy output because of it, and I think that's contributing to your outlook.  This doesn't happen in my Windows VM or on my Linux desktop.

![work in progress](http://i.imgur.com/5TMdhpS.png)

Don't worry too much about differences in the message view.  It will all be configurable and you can make it look exactly like Vintel if you want by the time I'm done (but I think better options will come to light).
