### ISSUE TITLE
Unable to Compile Linux Mint 18.1 64 Bit

### ISSUE THREAD

**Issue by schtufbox** [3vi1/IMP#8]
Despite having the requirements listed in the install.md file, and following the instructions, I'm unable to compile IMP.
Please find attached the output from compiling, hope it helps (I haven't compiled anything for 8 years, and never anything QT based so I'm clueless!)
[poo.txt](https://github.com/3vi1/IMP/files/917835/poo.txt)

**Comment by LaughingInPurgatory** [comment]
Additional note.  It's looking like an issue with Mint itself, or what version of qt or similar.  I switched to Ubuntu Gnome edition, and compiles right away with no issues at all.

**Comment by bmstettin** [comment]
The problem  occurs on system with qt4 and qt5 installed with preference to qt4.
`qmake --qt=5 ../src/imp.pro`
this command line  fixes it by telling the right qt version to qtchooser.

**Comment by LaughingInPurgatory** [comment]
Thanks, that's good to know. Is there any way I can help with adding other areas such as Malpais, The Spire and Oasa, Pure Blind, Etherium Reach etc?

**Comment by Rivil** [comment]
I have the same problem on same distro. 
qmake --qt=5 did not help :(

**Comment by bmstettin** [comment]
Open  the Makefile in find the line similar to this: 
`CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)`
add at the end "-std=c++11"
`CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES) -std=c++11`

I don't had the time to verify if the packages "clang" and "llvm"  are needet so if the fix doesnt work try it again after installing it.

the Problem occurs due to changes of the the standard c++ dialect beginning with the the major release 5 
[This link may be helpfull](https://gcc.gnu.org/gcc-6/porting_to.html)

since my c++ is only rudimentary im unable to solve this completely.

**Comment by Rivil** [comment]
Worked like a charm.
Thank you.

**Comment by bmstettin** [comment]
A fix for this issue is to add the following line to the imp.pro file 
`QMAKE_CXXFLAGS += -std=c++11`

in INSTALL.md change
```
qmake ../src/imp.pro
to
qmake --qt=5 ../src/imp.pro
```
